### ISSUE TITLE
memoise onLoad to avoid build-time dependency

### ISSUE THREAD

**Issue by tanho63** [SCasanova/f1dataR#154]
Hallo! Stumbled back here after seeing @pbulsink post about it on bluesky :grinning: 

Noticed that the package memoises at build time, i.e. directly inside the R/ source code files. This can cause some unexpected issues, e.g. the function body changing after a different package version is loaded/installed but still returning the previous one, or causing issues while being built on CRAN. 

package guidance suggests [memoising onLoad](https://memoise.r-lib.org/reference/memoise.html#details) which would help resolve this - nflreadr does it like this https://github.com/nflverse/nflreadr/blob/main/R/zzz.R

**Comment by SCasanova** [comment]
Thank you so much for bringing this up. Your comment comes mere hours after we re-submitted to CRAN haha so if we fail this time we'll be sure to re-submit with the changes or in the opposite case, implement on dev version

**Comment by pbulsink** [comment]
Thanks Tan, for this great suggestion!

This raises too the opportunity to cache to file system for persistent Ergast caching. 

We might, though, want to consider burying the cache to the `get_ergast_content()` level, instead of the user-accessed function level (i.e. `load_results()`, `load_pitstops()`, etc)? Thoughts @SCasanova?

I could likely do this at the same time as #153 if we want to just completely rewrite that core function.

**Comment by SCasanova** [comment]
If I understand the simple onLoad memoising, we need to completely eliminate `.*()` function naming, export un-memoised functions and then memoise on the onLoad function

**Comment by tanho63** [comment]
you can memoise unexported internal functions, they just need to be memoised inside onLoad

**Comment by SCasanova** [comment]
Closed by #165
