### ISSUE TITLE
Update Introduction vignette to highlight new features

### ISSUE THREAD

**Issue by SCasanova** [SCasanova/f1dataR#59]
I have planned to do this for a while but especially now that the session laps function has been added. Also inclusion of other vignettes

**Comment by SCasanova** [comment]
Perhaps examples should be added to the functions as well but this can also be done after the 1.0.0 move

**Comment by SCasanova** [comment]
Slightly irrelevant but it would be fun to release the 1.0.0 on June 21st (the 1 year anniversary of the package) if you're ok with that.

**Comment by pbulsink** [comment]
Lets do it. Package looks great for 1 year! 

Thoughts on submitting to CRAN once we hit stable 1.0?

**Comment by SCasanova** [comment]
Would love to submit to CRAN. I'm a bit nervous about the process but I think we're well on our way

**Comment by SCasanova** [comment]
Worked on by #108

**Comment by SCasanova** [comment]
What else should we do before CRAN? @pbulsink

**Comment by pbulsink** [comment]
Likely finish #108, come to a conclusion on #78 (do we need to do multi-driver function or just let the users do it?), look at #113, ensure our version number is correct, and then maybe go for it? If CRAN have additional suggestions after our first submit attempt we can have a better idea of what's needed.

Once submitted we'll have to do PRs to a dev/beta branch because CRAN would prefer updates only happen every few months.

**Comment by pbulsink** [comment]
Also working in [pbulsink/f1dataR:checks-before-cran](https://github.com/pbulsink/f1dataR/tree/checks-before-cran), so wait for a pr from there?

**Comment by SCasanova** [comment]
Yes maybe we can hold off on #78 as it's not necessarily essential. I'm with you on #113

**Comment by pbulsink** [comment]
As an alternative to implementing multi-driver #7,8 we could better
highlight (or reference in the function docs) loading 2+ drivers to compare
their telemetry in the plot in the Introduction vignette.

**Comment by SCasanova** [comment]
Closed by #109, #86
